title: qiankq's Blog
email: qiankq@zju.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  慢的乐趣怎么消失了呢？
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qiankeqin.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  qiankeqin

# Build settings
theme: minima
plugins:
  - jekyll-feed